#!/bin/bash

# Need classpath to be explicitly mentioned to include required jar files
CLASSPATH=.:java-json.jar
# Invoking the entrypoint file mainfile
# $@ represents all the command-line arguments passed to the script when it is executed.
#java -classpath "$CLASSPATH" Main.java "$@"
java -classpath "$CLASSPATH" SenderMain.java "$@"

chmod a+x 3700send